Module6 task1
htmlacademy-react/859219-what-to-watch-5 pull request #10
Opened 2020-11-14 15:01 UTC by Ekzaton

2020-11-16 20:38 UTC, Sasha-belokur requested changes

2020-11-16 20:38 UTC, Sasha-belokur commented on src/components/review-form/review-form.jsx
> +          />
1. Не уверен, что это работает, но даже если работает, обработчик должен висить на инпуте, а не диве.
2. У всех инпутов должен быть атрибут checked.
3. Все 5 инпутов между собой очень похожи. Завтра клиент захочет, чтобы фильм оценивался по 10-бальной шкале и нам придется делать ctrl+c & ctrl+v. Подумаю, как можно динамически рисовать любое кол-во интпутов для рейтинга.

2020-11-16 20:38 UTC, Sasha-belokur commented on src/components/review-form/review-form.jsx
> +        />
Здесь тоже самое, компонент должен быть контролируемый и у него должно быть value из state

2020-11-17 09:05 UTC, Ekzaton commented on src/components/review-form/review-form.jsx
> +          />
Исправил

2020-11-17 09:06 UTC, Ekzaton commented on src/components/review-form/review-form.jsx
> +        />
Исправил

2020-11-18 08:00 UTC, merged