Created 'with-player.jsx' hoc
htmlacademy-react/859219-what-to-watch-5 pull request #11
Opened 2020-11-18 08:24 UTC by Ekzaton

2020-11-18 15:24 UTC, Sasha-belokur requested changes

2020-11-18 15:24 UTC, Sasha-belokur commented on package.json
> +    "moment": "2.29.1",
На самом деле момент уже умирает, у них даже на [сайте это написано](https://momentjs.com/docs/#/-project-status/) . Лучше посмотреть в сторону других [альтернатив](https://github.com/you-dont-need/You-Dont-Need-Momentjs)

P.s. если не хочется переписывать, здесь можно оставить уже moment, но на будущее лучше знать про альтернативы.

2020-11-18 15:24 UTC, Sasha-belokur commented on src/components/main/main.jsx
> +                <Link to="/player/:id" className="btn btn--play movie-card__button">
Здесь `:id` должен быть id того фильма, который мы воспроизводим на весь экран. 
И везде где мы ссылаемся на фильм, тоже.

2020-11-18 15:25 UTC, merged

2020-11-20 18:10 UTC, Ekzaton commented on package.json
> +    "moment": "2.29.1",
С альтернативами ознакомился, но пока оставил moment)

2020-11-20 18:10 UTC, Ekzaton commented on src/components/main/main.jsx
> +                <Link to="/player/:id" className="btn btn--play movie-card__button">
Поправил все маршруты